unit_labels = {
    'abampere': 'Abampere',
    'abampere per square centimeter': 'AbamperePerSquareCentimeter',
    'abcoulomb': 'Abcoulomb',
    'abcoulomb per square centimeter': 'AbcoulombPerSquareCentimeter',
    'abfarad': 'Abfarad',
    'abfarad per centimeter': 'AbfaradPerCentimeter',
    'abhenry': 'Abhenry',
    'abohm': 'Abohm',
    'absiemen': 'Absiemen',
    'abtesla': 'Abtesla',
    'abvolt': 'Abvolt',
    'abvolt centimeter': 'AbvoltCentimeter',
    'abvolt per centimeter': 'AbvoltPerCentimeter',
    'abvolt second': 'AbvoltSecond',
    'acre': 'Acre',
    'acre foot': 'AcreFoot',
    'afghani': 'Afghani',
    'algerian dinar': 'AlgerianDinar',
    'ampere': 'Ampere',
    'ampere hour': 'AmpereHour',
    'ampere per degree': 'AmperePerDegree',
    'ampere per joule': 'AmperePerJoule',
    'ampere per meter': 'AmperePerMeter',
    'ampere per radian': 'AmperePerRadian',
    'ampere per square meter': 'AmperePerSquareMeter',
    'ampere turn': 'AmpereTurn',
    'ampere turn per inch': 'AmpereTurnPerInch',
    'ampere turn per meter': 'AmpereTurnPerMeter',
    'angstrom': 'Angstrom',
    'arc minute': 'ArcMinute',
    'arc second': 'ArcSecond',
    'are': 'Are',
    'argentine peso': 'ArgentinePeso',
    'armenian dram': 'ArmenianDram',
    'aruban guilder': 'ArubanGuilder',
    'astronomical unit': 'AstronomicalUnit',
    'atomic mass unit': 'AtomicMassUnit',
    'atomic number': 'AtomicNumber',
    'atomic system of units': 'SystemOfUnits_Atomic',
    'atto': 'Atto',
    'australian dollar': 'AustralianDollar',
    'azerbaijanian manat': 'AzerbaijanianManat',
    'bahamian dollar': 'BahamianDollar',
    'bahraini dinar': 'BahrainiDinar',
    'baht': 'Baht',
    'balboa': 'Balboa',
    'ban': 'Ban',
    'bangladeshi taka': 'BangladeshiTaka',
    'bar': 'Bar',
    'barbados dollar': 'BarbadosDollar',
    'barn': 'Barn',
    'barrel': 'Barrel',
    'becquerel': 'Becquerel',
    'belarussian ruble': 'BelarussianRuble',
    'belize dollar': 'BelizeDollar',
    'bermuda dollar': 'BermudaDollar',
    'biot': 'Biot',
    'bit': 'Bit',
    'bits per second': 'BitsPerSecond',
    'board foot': 'BoardFoot',
    'bolivian mvdol (funds code)': 'BolivianMvdol',
    'boliviano': 'Boliviano',
    'brazilian real': 'BrazilianReal',
    'breath': 'Breath',
    'breath per minute': 'BreathPerMinute',
    'british thermal unit - international steam table': 'BritishThermalUnitInternationalTable',
    'british thermal unit - thermochemical calorie': 'BritishThermalUnitThermochemical',
    'brunei dollar': 'BruneiDollar',
    'btu foot': 'BtuFoot',
    'btu foot per square foot hour degree fahrenheit': 'BtuFootPerSquareFootHourDegreeFahrenheit',
    'btu inch': 'BtuInch',
    'btu inch per square foot hour degree fahrenheit': 'BtuInchPerSquareFootHourDegreeFahrenheit',
    'btu inch per square foot second degree fahrenheit': 'BtuInchPerSquareFootSecondDegreeFahrenheit',
    'btu per degree fahrenheit': 'BtuPerDegreeFahrenheit',
    'btu per degree rankine': 'BtuPerDegreeRankine',
    'btu per hour': 'BtuPerHour',
    'btu per hour square foot': 'BtuPerHourSquareFoot',
    'btu per pound': 'BtuPerPound',
    'btu per pound degree fahrenheit': 'BtuPerPoundDegreeFahrenheit',
    'btu per pound degree rankine': 'BtuPerPoundDegreeRankine',
    'btu per pound mole': 'BtuPerPoundMole',
    'btu per pound mole degree fahrenheit': 'BtuPerPoundMoleDegreeFahrenheit',
    'btu per second': 'BtuPerSecond',
    'btu per second square foot': 'BtuPerSecondSquareFoot',
    'btu per square foot': 'BtuPerSquareFoot',
    'btu per square foot hour degree fahrenheit': 'BtuPerSquareFootHourDegreeFahrenheit',
    'btu per square foot second degree fahrenheit': 'BtuPerSquareFootSecondDegreeFahrenheit',
    'bulgarian lev': 'BulgarianLev',
    'burundian franc': 'BurundianFranc',
    'bushel': 'Bushel',
    'byte': 'Byte',
    'calorie per centimeter second degree celsius': 'KilocaloriePerCentimeterSecondDegreeCelsius',
    'calorie per gram degree celsius': 'KilocaloriePerGramDegreeCelsius',
    'canadian dollar': 'CanadianDollar',
    'candela': 'Candela',
    'candela per square inch': 'CandelaPerSquareInch',
    'candela per square meter': 'CandelaPerSquareMeter',
    'candle': 'Candle',
    'candlepower': 'Candlepower',
    'cape verde escudo': 'CapeVerdeEscudo',
    'carat': 'Carat',
    'cayman islands dollar': 'CaymanIslandsDollar',
    'cedi': 'Cedi',
    'centi': 'Centi',
    'centimeter': 'Centimeter',
    'centimeter of water': 'CentimeterOfWater',
    'centimeter per second': 'CentimeterPerSecond',
    'centimeter per second squared': 'CentimeterPerSecondSquared',
    'centimeter second degree celsius': 'CentimeterSecondDegreeCelsius',
    'centipoise': 'Centipoise',
    'centistokes': 'Centistokes',
    'cfa franc bceao': 'CFAFrancBCEAO',
    'cfa franc beac': 'CFAFrancBEAC',
    'cfp franc': 'CFPFranc',
    'cgs system of units': 'SystemOfUnits_CGS',
    'cgs-emu system of units': 'SystemOfUnits_CGS-EMU',
    'cgs-esu system of units': 'SystemOfUnits_CGS-ESU',
    'cgs-gauss system of units': 'SystemOfUnits_CGS-Gauss',
    'chain': 'Chain',
    'chilean peso': 'ChileanPeso',
    'circular mil': 'CircularMil',
    'clo': 'Clo',
    'colombian peso': 'ColombianPeso',
    'colony forming unit': 'ColonyFormingUnit',
    'comoro franc': 'ComoroFranc',
    'convertible marks': 'ConvertibleMark',
    'cord': 'Cord',
    'cordoba oro': 'CordobaOro',
    'costa rican colon': 'CostaRicanColon',
    'coulomb': 'Coulomb',
    'coulomb meter': 'CoulombMeter',
    'coulomb per cubic meter': 'CoulombPerCubicMeter',
    'coulomb per kilogram': 'CoulombPerKilogram',
    'coulomb per meter': 'CoulombPerMeter',
    'coulomb per mole': 'CoulombPerMole',
    'coulomb per square meter': 'CoulombPerSquareMeter',
    'coulomb square meter': 'CoulombSquareMeter',
    'croatian kuna': 'CroatianKuna',
    'cuban peso': 'CubanPeso',
    'cubic centimeter': 'CubicCentimeter',
    'cubic coulomb meter per square joule': 'CubicCoulombMeterPerSquareJoule',
    'cubic foot': 'CubicFoot',
    'cubic foot per minute': 'CubicFootPerMinute',
    'cubic foot per second': 'CubicFootPerSecond',
    'cubic inch': 'CubicInch',
    'cubic inch per minute': 'CubicInchPerMinute',
    'cubic kilometer per second squared': 'CubicKilometerPerSecondSquared',
    'cubic meter': 'CubicMeter',
    'cubic meter per hour': 'CubicMeterPerHour',
    'cubic meter per kelvin': 'CubicMeterPerKelvin',
    'cubic meter per kilogram': 'CubicMeterPerKilogram',
    'cubic meter per kilogram second squared': 'CubicMeterPerKilogramSecondSquared',
    'cubic meter per mole': 'CubicMeterPerMole',
    'cubic meter per second': 'CubicMeterPerSecond',
    'cubic meter per second squared': 'CubicMeterPerSecondSquared',
    'cubic mile': 'CubicMile',
    'cubic millimeter': 'CubicMillimeter',
    'cubic yard': 'CubicYard',
    'cubic yard per minute': 'CubicYardPerMinute',
    'curie': 'Curie',
    'cyprus pound': 'CyprusPound',
    'czech koruna': 'CzechKoruna',
    'dalasi': 'Dalasi',
    'dalton': 'Dalton',
    'danish krone': 'DanishKrone',
    'day': 'Day',
    'day sidereal': 'DaySidereal',
    'debye': 'Debye',
    'deca': 'Deca',
    'deci': 'Deci',
    'decibel': 'Decibel',
    'decibel carrier unit': 'DecibelCarrier',
    'decibel referred to 1mw': 'DecibelReferredToOneMilliwatt',
    'decimeter': 'Decimeter',
    'degree angle': 'DegreeAngle',
    'degree celsius': 'DegreeCelsius',
    'degree celsius centimeter': 'DegreeCelsiusCentimeter',
    'degree celsius per hour': 'DegreeCelsiusPerHour',
    'degree celsius per minute': 'DegreeCelsiusPerMinute',
    'degree celsius per second': 'DegreeCelsiusPerSecond',
    'degree centigrade': 'DegreeCentigrade',
    'degree fahrenheit': 'DegreeFahrenheit',
    'degree fahrenheit hour': 'DegreeFahrenheitHour',
    'degree fahrenheit hour per btu': 'DegreeFahrenheitHourPerBtu',
    'degree fahrenheit per hour': 'DegreeFahrenheitPerHour',
    'degree fahrenheit per minute': 'DegreeFahrenheitPerMinute',
    'degree fahrenheit per second': 'DegreeFahrenheitPerSecond',
    'degree per hour': 'DegreePerHour',
    'degree per minute': 'DegreePerMinute',
    'degree per second': 'DegreePerSecond',
    'degree per second squared': 'DegreePerSecondSquared',
    'degree rankine': 'DegreeRankine',
    'degree rankine per hour': 'DegreeRankinePerHour',
    'degree rankine per minute': 'DegreeRankinePerMinute',
    'degree rankine per second': 'DegreeRankinePerSecond',
    'denar': 'Denar',
    'denier': 'Denier',
    'diopter': 'Diopter',
    'djibouti franc': 'DjiboutiFranc',
    'dobra': 'Dobra',
    'dominican peso': 'DominicanPeso',
    'dry gallon us': 'DryGallonUS',
    'dyne': 'Dyne',
    'dyne centimeter': 'DyneCentimeter',
    'dyne per square centimeter': 'DynePerSquareCentimeter',
    'east caribbean dollar': 'EastCaribbeanDollar',
    'egyptian pound': 'EgyptianPound',
    'electron volt': 'ElectronVolt',
    'electron volt per kelvin': 'ElectronVoltPerKelvin',
    'electron volt per tesla': 'ElectronVoltPerTesla',
    'electron volt second': 'ElectronVoltSecond',
    'erg': 'Erg',
    'erg per cubic centimeter': 'ErgPerCubicCentimeter',
    'erg per gram': 'ErgPerGram',
    'erg per second': 'ErgPerSecond',
    'erg per square centimeter second': 'ErgPerSquareCentimeterSecond',
    'erg second': 'ErgSecond',
    'ethiopian birr': 'EthiopianBirr',
    'euro': 'Euro',
    'european composite unit (eurco) (bonds market unit)': 'EuropeanCompositeUnit',
    'european monetary unit (e.m.u.-6) (bonds market unit)': 'EuropeanMonetaryUnit',
    'european unit of account 17 (e.u.a.-17) (bonds market unit)': 'EuropeanUnitOfAccount17',
    'european unit of account 9 (e.u.a.-9) (bonds market unit)': 'EuropeanUnitOfAccount9',
    'exa': 'Exa',
    'exbi': 'Exbi',
    'falkland islands pound': 'FalklandIslandsPound',
    'farad': 'Farad',
    'farad per meter': 'FaradPerMeter',
    'faraday': 'Faraday',
    'fathom': 'Fathom',
    'femto': 'Femto',
    'femtometer': 'Femtometer',
    'fermi': 'Fermi',
    'fiji dollar': 'FijiDollar',
    'flight': 'Flight',
    'foot': 'Foot',
    'foot candle': 'FootCandle',
    'foot lambert': 'FootLambert',
    'foot of water': 'FootOfWater',
    'foot per hour': 'FootPerHour',
    'foot per minute': 'FootPerMinute',
    'foot per second': 'FootPerSecond',
    'foot per second squared': 'FootPerSecondSquared',
    'foot pound force': 'FootPoundForce',
    'foot pound force per hour': 'FootPoundForcePerHour',
    'foot pound force per minute': 'FootPoundForcePerMinute',
    'foot pound force per second': 'FootPoundForcePerSecond',
    'foot pound force per square foot second': 'FootPoundForcePerSquareFootSecond',
    'foot pound force per square meter': 'FootPoundForcePerSquareMeter',
    'foot pound force second': 'FootPoundForceSecond',
    'foot pound per square foot': 'FootPoundForcePerSquareFoot',
    'foot poundal': 'FootPoundal',
    'forint': 'Forint',
    'fractional area': 'FractionalArea',
    'frame per second': 'FramePerSecond',
    'franc congolais': 'FrancCongolais',
    'franklin': 'Franklin',
    'furlong': 'Furlong',
    'gal': 'Gal',
    'gamma': 'Gamma',
    'gauss': 'Gauss',
    'gibi': 'Gibi',
    'gibraltar pound': 'GibraltarPound',
    'giga': 'Giga',
    'giga electron volt': 'GigaElectronVolt',
    'gigahertz': 'GigaHertz',
    'gilbert': 'Gilbert',
    'gold (one troy ounce)': 'Gold-OunceTroy',
    'gold franc (special settlement currency)': 'GoldFranc',
    'gon': 'Gon',
    'grad': 'Grad',
    'grade': 'Grade',
    'grain': 'Grain',
    'grain per gallon': 'GrainPerGallon',
    'gram': 'Gram',
    'gram degree celsius': 'GramDegreeCelsius',
    'gravity': 'Gravity',
    'gray': 'Gray',
    'gray per second': 'GrayPerSecond',
    'guarani': 'Guarani',
    'guinea franc': 'GuineaFranc',
    'guyana dollar': 'GuyanaDollar',
    'haiti gourde': 'HaitiGourde',
    'hartree': 'Hartree',
    'heart beat': 'HeartBeat',
    'heart beat per minute': 'HeartBeatsPerMinute',
    'hectare': 'Hectare',
    'hecto': 'Hecto',
    'henry': 'Henry',
    'henry per meter': 'HenryPerMeter',
    'hertz': 'Hertz',
    'hertz per kelvin': 'HertzPerKelvin',
    'hertz per tesla': 'HertzPerTesla',
    'hertz per volt': 'HertzPerVolt',
    'hong kong dollar': 'HongKongDollar',
    'horsepower': 'Horsepower',
    'horsepower boiler': 'HorsepowerBoiler',
    'horsepower electric': 'HorsepowerElectric',
    'horsepower metric': 'HorsepowerMetric',
    'horsepower water': 'HorsepowerWater',
    'hour': 'Hour',
    'hour sidereal': 'HourSidereal',
    'hour square foot': 'HourSquareFoot',
    'hryvnia': 'Hryvnia',
    'hundred weight - long': 'HundredWeightLong',
    'hundred weight - short': 'HundredWeightShort',
    'iceland krona': 'IcelandKrona',
    'imperial gallon': 'GallonImperial',
    'imperial ounce': 'OunceImperial',
    'imperial pint': 'PintImperial',
    'inch': 'Inch',
    'inch of mercury': 'InchOfMercury',
    'inch of water': 'InchOfWater',
    'inch per second': 'InchPerSecond',
    'inch per second squared': 'InchPerSecondSquared',
    'inch pound force': 'InchPoundForce',
    'indian rupee': 'IndianRupee',
    'international system of units': 'SystemOfUnits_SI',
    'international unit': 'InternationalUnit',
    'international unit per liter': 'InternationalUnitPerLiter',
    'inverse second': 'PerSecond',
    'iranian rial': 'IranianRial',
    'iraqi dinar': 'IraqiDinar',
    'iso 4217 currencies': 'SystemOfUnits_ISO4217-Currencies',
    'jamaican dollar': 'JamaicanDollar',
    'japanese yen': 'JapaneseYen',
    'jordanian dinar': 'JordanianDinar',
    'joule': 'Joule',
    'joule meter per mole': 'JouleMeterPerMole',
    'joule per cubic meter': 'JoulePerCubicMeter',
    'joule per cubic meter kelvin': 'JoulePerCubicMeterKelvin',
    'joule per kelvin': 'JoulePerKelvin',
    'joule per kilogram': 'JoulePerKilogram',
    'joule per kilogram kelvin': 'JoulePerKilogramKelvin',
    'joule per kilogram kelvin per cubic meter': 'JoulePerKilogramKelvinPerCubicMeter',
    'joule per kilogram kelvin per pascal': 'JoulePerKilogramKelvinPerPascal',
    'joule per mole': 'JoulePerMole',
    'joule per mole kelvin': 'JoulePerMoleKelvin',
    'joule per square meter': 'JoulePerSquareMeter',
    'joule per square tesla': 'JoulePerSquareTesla',
    'joule per tesla': 'JoulePerTesla',
    'joule second': 'JouleSecond',
    'joule second per mole': 'JouleSecondPerMole',
    'katal': 'Katal',
    'kelvin': 'Kelvin',
    'kelvin per hour': 'KelvinPerHour',
    'kelvin per minute': 'KelvinPerMinute',
    'kelvin per second': 'KelvinPerSecond',
    'kelvin per tesla': 'KelvinPerTesla',
    'kelvin per watt': 'KelvinPerWatt',
    'kenyan shilling': 'KenyanShilling',
    'kibi': 'Kibi',
    'kilo': 'Kilo',
    'kilo electron volt': 'KiloElectronVolt',
    'kilo electron volt per micrometer': 'KiloElectronVoltPerMicrometer',
    'kilobit per second': 'KilobitsPerSecond',
    'kilocalorie': 'Kilocalorie',
    'kilocalorie per gram': 'KilocaloriePerGram',
    'kilocalorie per minute': 'KilocaloriePerMinute',
    'kilocalorie per mole': 'KilocaloriePerMole',
    'kilocalorie per mole degree celsius': 'KilocaloriePerMoleDegreeCelsius',
    'kilocalorie per second': 'KilocaloriePerSecond',
    'kilocalorie per square centimeter': 'KilocaloriePerSquareCentimeter',
    'kilocalorie per square centimeter minute': 'KilocaloriePerSquareCentimeterMinute',
    'kilocalorie per square centimeter second': 'KilocaloriePerSquareCentimeterSecond',
    'kilogram': 'Kilogram',
    'kilogram force': 'KilogramForce',
    'kilogram force meter': 'KilogramForceMeter',
    'kilogram force per square centimeter': 'KilogramForcePerSquareCentimeter',
    'kilogram kelvin': 'KilogramKelvin',
    'kilogram meter per second': 'KilogramMeterPerSecond',
    'kilogram meter squared': 'KilogramMeterSquared',
    'kilogram per cubic meter': 'KilogramPerCubicMeter',
    'kilogram per hour': 'KilogramPerHour',
    'kilogram per meter': 'KilogramPerMeter',
    'kilogram per mole': 'KilogramPerMole',
    'kilogram per second': 'KilogramPerSecond',
    'kilogram per square meter': 'KilogramPerSquareMeter',
    'kilogram second squared': 'KilogramSecondSquared',
    'kilohertz': 'KiloHertz',
    'kilometer ': 'Kilometer',
    'kilometer per hour': 'KilometerPerHour',
    'kilometer per second': 'KilometerPerSecond',
    'kilopascal': 'KiloPascal',
    'kilopascal absolute': 'KiloPascalAbsolute',
    'kilopond': 'KiloPond',
    'kilowatt': 'Kilowatt',
    'kilowatthour': 'Kilowatthour',
    'kina': 'Kina',
    'kip': 'Kip',
    'kip per square inch': 'KipPerSquareInch',
    'knot': 'Knot',
    'knot per second': 'KnotPerSecond',
    'kroon': 'Kroon',
    'kuwaiti dinar': 'KuwaitiDinar',
    'kwanza': 'Kwanza',
    'kyat': 'Kyat',
    'lambert': 'Lambert',
    'laos kip': 'LaosKip',
    'lari': 'Lari',
    'latvian lats': 'LatvianLats',
    'launch': 'Launch',
    'lebanese pound': 'LebanesePound',
    'lek': 'Lek',
    'lempira': 'Lempira',
    'leone': 'Leone',
    'liberian dollar': 'LiberianDollar',
    'libyan dinar': 'LibyanDinar',
    'light year': 'LightYear',
    'lilangeni': 'Lilangeni',
    'liter': 'Liter',
    'lithuanian litas': 'LithuanianLitas',
    'loti': 'Loti',
    'lumen': 'Lumen',
    'lumen per watt': 'LumenPerWatt',
    'lumen second': 'LumenSecond',
    'lux': 'Lux',
    'mach': 'Mach',
    'malagasy ariary': 'MalagasyAriary',
    'malawi kwacha': 'MalawiKwacha',
    'malaysian ringgit': 'MalaysianRinggit',
    'maltese lira': 'MalteseLira',
    'manat': 'Manat',
    'mauritius rupee': 'MauritiusRupee',
    'maxwell': 'Maxwell',
    'mebi': 'Mebi',
    'mega': 'Mega',
    'mega electron volt': 'MegaElectronVolt',
    'mega electron volt femtometer': 'MegaElectronVoltFemtometer',
    'mega electron volt per centimeter': 'MegaElectronVoltPerCentimeter',
    'mega electron volt per speed of light': 'MegaElectronVoltPerSpeedOfLight',
    'mega hertz per kelvin': 'MegaHertzPerKelvin',
    'mega hertz per tesla': 'MegaHertzPerTesla',
    'megabit per second': 'MegabitsPerSecond',
    'megahertz': 'MegaHertz',
    'meter': 'Meter',
    'meter kelvin': 'MeterKelvin',
    'meter kelvin per watt': 'MeterKelvinPerWatt',
    'meter kilogram': 'MeterKilogram',
    'meter per farad': 'MeterPerFarad',
    'meter per hour': 'MeterPerHour',
    'meter per kelvin': 'MeterPerKelvin',
    'meter per minute': 'MeterPerMinute',
    'meter per second': 'MeterPerSecond',
    'meter per second squared': 'MeterPerSecondSquared',
    'metical': 'Metical',
    'metric ton': 'MetricTon',
    'mexican peso': 'MexicanPeso',
    'mexican unidad de inversion (udi) (funds code)': 'MexicanUnidadDeInversion',
    'mho': 'Mho',
    'micro': 'Micro',
    'microfarad': 'MicroFarad',
    'microgravity': 'Microgravity',
    'microhenry': 'MicroHenry',
    'microinch': 'MicroInch',
    'micrometer': 'Micrometer',
    'microsecond': 'MicroSecond',
    'microtorr': 'MicroTorr',
    'mil angle (nato)': 'MilAngle',
    'mil length': 'MilLength',
    'mile - international standard': 'MileInternational',
    'mile per hour': 'MilePerHour',
    'mile per minute': 'MilePerMinute',
    'mile us statute': 'MileUSStatute',
    'milli': 'Milli',
    'millibar': 'Millibar',
    'milligravity': 'Milligravity',
    'millihenry': 'MilliHenry',
    'millimeter': 'Millimeter',
    'millimeter of mercury': 'MillimeterOfMercury',
    'millimeter of mercury - absolute': 'MillimeterOfMercuryAbsolute',
    'million us dollars': 'MillionUSDollars',
    'million us dollars per flight': 'MillionDollarsPerFlight',
    'million us dollars per year': 'MillionDollarsPerYear',
    'millisecond': 'MilliSecond',
    'millitorr': 'MilliTorr',
    'minute angle': 'MinuteAngle',
    'minute sidereal': 'MinuteSidereal',
    'minute time': 'MinuteTime',
    'mks system of units': 'SystemOfUnits_MKS',
    'moldovan leu': 'MoldovanLeu',
    'mole': 'Mole',
    'mole degree celsius': 'MoleDegreeCelsius',
    'mole kelvin': 'MoleKelvin',
    'mole per cubic meter': 'MolePerCubicMeter',
    'mole per kilogram': 'MolePerKilogram',
    'moroccan dirham': 'MoroccanDirham',
    'naira': 'Naira',
    'nakfa': 'Nakfa',
    'namibian dollar': 'NamibianDollar',
    'nano': 'Nano',
    'nanofarad': 'NanoFarad',
    'nat': 'Nat',
    'nautical mile': 'NauticalMile',
    'nautical mile per hour': 'NauticalMilePerHour',
    'nautical mile per minute': 'NauticalMilePerMinute',
    'nepalese rupee': 'NepaleseRupee',
    'nephelometry turbidity unit': 'NephelometricTurbidityUnit',
    'netherlands antillian guilder': 'NetherlandsAntillianGuilder',
    'new israeli shekel': 'NewIsraeliShekel',
    'new taiwan dollar': 'NewTaiwanDollar',
    'new turkish lira': 'NewTurkishLira',
    'new zealand dollar': 'NewZealandDollar',
    'newton': 'Newton',
    'newton meter': 'NewtonMeter',
    'newton per coulomb': 'NewtonPerCoulomb',
    'newton per kilogram': 'NewtonPerKilogram',
    'newton per meter': 'NewtonPerMeter',
    'ngultrum': 'Ngultrum',
    'north korean won': 'NorthKoreanWon',
    'norwegian krone': 'NorwegianKrone',
    'nuevo sol': 'NuevoSol',
    'number': 'Number',
    'number per year': 'NumberPerYear',
    'nutritional calorie': 'CalorieNutritional',
    'oersted': 'Oersted',
    'oersted centimeter': 'OerstedCentimeter',
    'ohm': 'Ohm',
    'ouguiya': 'Ouguiya',
    'ounce force': 'OunceForce',
    'ounce force inch': 'OunceForceInch',
    'ounce mass': 'OunceMass',
    'ounce per cubic inch': 'OuncePerCubicInch',
    'ounce per gallon': 'OuncePerGallon',
    'ounce per square foot': 'OuncePerSquareFoot',
    'ounce per square yard': 'OuncePerSquareYard',
    'ounce troy': 'OunceTroy',
    "pa'anga": 'Paanga',
    'pakistan rupee': 'PakistanRupee',
    'palladium (one troy ounce)': 'Palladium-OunceTroy',
    'parsec': 'Parsec',
    'pascal': 'Pascal',
    'pascal per hour': 'PascalPerHour',
    'pascal per minute': 'PascalPerMinute',
    'pascal per second': 'PascalPerSecond',
    'pascal second': 'PascalSecond',
    'pataca': 'Pataca',
    'pebi': 'Pebi',
    'penny weight': 'PennyWeight',
    'per cubic meter': 'PerCubicMeter',
    'per meter kelvin unit': 'PerMeterKelvin',
    'per meter unit': 'PerMeter',
    'per mole unit': 'PerMole',
    'per square giga electron volt unit': 'PerSquareGigaElectronVolt',
    'per tesla meter unit': 'PerTeslaMeter',
    'per tesla second unit': 'PerTeslaSecond',
    'percent': 'Percent',
    'person': 'Person',
    'peso uruguayo': 'UruguayPeso',
    'peta': 'Peta',
    'philippine peso': 'PhilippinePeso',
    'phot': 'Phot',
    'pica': 'Pica',
    'pico': 'Pico',
    'picofarad': 'PicoFarad',
    'planck area': 'PlanckArea',
    'planck charge': 'PlanckCharge',
    'planck current': 'PlanckCurrent',
    'planck current density': 'PlanckCurrentDensity',
    'planck density': 'PlanckDensity',
    'planck energy': 'PlanckEnergy',
    'planck force': 'PlanckForce',
    'planck frequency': 'PlanckFrequency',
    'planck length': 'PlanckLength',
    'planck mass': 'PlanckMass',
    'planck momentum': 'PlanckMomentum',
    'planck power': 'PlanckPower',
    'planck pressure': 'PlanckPressure',
    'planck resistance': 'PlanckResistance',
    'planck system of units': 'SystemOfUnits_Planck',
    'planck temperature': 'PlanckTemperature',
    'planck time': 'PlanckTime',
    'planck volt': 'PlanckVolt',
    'planck volume': 'PlanckVolume',
    'platinum (one troy ounce)': 'Platinum-OunceTroy',
    'point': 'Point',
    'poise': 'Poise',
    'pound degree fahrenheit': 'PoundDegreeFahrenheit',
    'pound degree rankine': 'PoundDegreeRankine',
    'pound force': 'PoundForce',
    'pound force foot': 'PoundForceFoot',
    'pound force inch': 'PoundForceInch',
    'pound force per foot': 'PoundForcePerFoot',
    'pound force per inch': 'PoundForcePerInch',
    'pound force per pound': 'PoundForcePerPound',
    'pound force per square foot': 'PoundForcePerSquareFoot',
    'pound force per square inch': 'PoundForcePerSquareInch',
    'pound force per square inch second': 'PoundForcePerSquareInchSecond',
    'pound force second per square foot': 'PoundForceSecondPerSquareFoot',
    'pound force second per square inch': 'PoundForceSecondPerSquareInch',
    'pound mass': 'PoundMass',
    'pound mole': 'PoundMole',
    'pound mole degree fahrenheit': 'PoundMoleDegreeFahrenheit',
    'pound per cubic foot': 'PoundPerCubicFoot',
    'pound per cubic inch': 'PoundPerCubicInch',
    'pound per cubic meter': 'PoundPerCubicMeter',
    'pound per cubic yard': 'PoundPerCubicYard',
    'pound per foot': 'PoundPerFoot',
    'pound per foot hour': 'PoundPerFootHour',
    'pound per foot second': 'PoundPerFootSecond',
    'pound per gallon': 'PoundPerGallon',
    'pound per hour': 'PoundPerHour',
    'pound per inch': 'PoundPerInch',
    'pound per minute': 'PoundPerMinute',
    'pound per square foot': 'PoundPerSquareFoot',
    'pound sterling': 'PoundSterling',
    'pound troy': 'PoundTroy',
    'poundal': 'Poundal',
    'poundal per square foot': 'PoundalPerSquareFoot',
    'pula': 'Pula',
    'qatari rial': 'QatariRial',
    'quad': 'Quad',
    'quartic coulomb meter per cubic energy': 'QuarticCoulombMeterPerCubicEnergy',
    'quetzal': 'Quetzal',
    'rad': 'Rad',
    'radian': 'Radian',
    'radian per hour': 'RadianPerHour',
    'radian per second': 'RadianPerSecond',
    'radian per second squared': 'RadianPerSecondSquared',
    'register ton': 'RegisterTon',
    'relative permeability': 'RelativePermeability',
    'relative permittivity': 'RelativePermittivity',
    'rem': 'Rem',
    'revolution': 'Revolution',
    'revolution per hour': 'RevolutionPerHour',
    'revolution per minute': 'RevolutionPerMinute',
    'revolution per second': 'RevolutionPerSecond',
    'revolution per second squared': 'RevolutionPerSecondSquared',
    'rial omani': 'OmaniRial',
    'riel': 'Riel',
    'rod': 'Rod',
    'roentgen': 'Roentgen',
    'romanian new leu': 'RomanianNeLeu',
    'rufiyaa': 'Rufiyaa',
    'rupiah': 'Rupiah',
    'russian ruble': 'RussianRuble',
    'rwanda franc': 'RwandaFranc',
    'saint helena pound': 'SaintHelenaPound',
    'samoan tala': 'SamoanTala',
    'sample per second': 'SamplePerSecond',
    'saudi riyal': 'SaudiRiyal',
    'second': 'SecondTime',
    'second angle': 'SecondAngle',
    'second square foot': 'SecondSquareFoot',
    'second time squared': 'SecondTimeSquared',
    'serbian dinar': 'SerbianDinar',
    'seychelles rupee': 'SeychellesRupee',
    'shake': 'Shake',
    'short ton per hour': 'TonShortPerHour',
    'siemens': 'Siemens',
    'sievert': 'Sievert',
    'silver (one troy ounce)': 'Silver-OunceTroy',
    'singapore dollar': 'SingaporeDollar',
    'slovak koruna': 'SlovakKoruna',
    'slug': 'Slug',
    'slug per cubic foot': 'SlugPerCubicFoot',
    'slug per foot': 'SlugPerFoot',
    'slug per foot second': 'SlugPerFootSecond',
    'slug per second': 'SlugPerSecond',
    'slug per square foot': 'SlugPerSquareFoot',
    'solomon islands dollar': 'SolomonIslandsDollar',
    'som': 'Som',
    'somali shilling': 'SomaliShilling',
    'somoni': 'Somoni',
    'south african rand': 'SouthAfricanRand',
    'south korean won': 'SouthKoreanWon',
    'special drawing rights': 'SpecialDrawingRights',
    'square centimeter': 'SquareCentimeter',
    'square centimeter minute': 'SquareCentimeterMinute',
    'square centimeter second': 'SquareCentimeterSecond',
    'square coulomb meter per joule': 'SquareCoulombMeterPerJoule',
    'square degree': 'SquareDegree',
    'square foot': 'SquareFoot',
    'square foot degree fahrenheit': 'SquareFootDegreeFahrenheit',
    'square foot hour degree fahrenheit': 'SquareFootHourDegreeFahrenheit',
    'square foot hour degree fahrenheit per btu': 'SquareFootHourDegreeFahrenheitPerBtu',
    'square foot per btu inch': 'SquareFootPerBtuInch',
    'square foot per hour': 'SquareFootPerHour',
    'square foot per second': 'SquareFootPerSecond',
    'square foot second degree fahrenheit': 'SquareFootSecondDegreeFahrenheit',
    'square inch': 'SquareInch',
    'square meter': 'SquareMeter',
    'square meter kelvin': 'SquareMeterKelvin',
    'square meter kelvin per watt': 'SquareMeterKelvinPerWatt',
    'square meter per kelvin': 'SquareMeterPerKelvin',
    'square meter per second': 'SquareMeterPerSecond',
    'square meter steradian': 'SquareMeterSteradian',
    'square mile': 'SquareMile',
    'square yard': 'SquareYard',
    'sri lanka rupee': 'SriLankaRupee',
    'standard atmosphere': 'AtmosphereStandard',
    'statampere': 'Statampere',
    'statampere per square centimeter': 'StatamperePerSquareCentimeter',
    'statcoulomb': 'Statcoulomb',
    'statcoulomb per mole': 'StatcoulombPerMole',
    'statcoulomb per square centimeter': 'StatcoulombPerSquareCentimeter',
    'statfarad': 'Statfarad',
    'stathenry': 'Stathenry',
    'stathenry per centimeter': 'StathenryPerCentimeter',
    'statmho': 'Statmho',
    'statohm': 'Statohm',
    'statvolt': 'Statvolt',
    'statvolt centimeter': 'StatvoltCentimeter',
    'statvolt per centimeter': 'StatvoltPerCentimeter',
    'steradian': 'Steradian',
    'stere': 'Stere',
    'stilb': 'Stilb',
    'stokes': 'Stokes',
    'sudanese pound': 'SudanesePound',
    'surinam dollar': 'SurinamDollar',
    'swedish krona': 'SwedishKrona',
    'swiss franc': 'SwissFranc',
    'syrian pound': 'SyrianPound',
    'system of units_imperial': 'SystemOfUnits_Imperial',
    'tablespoon': 'Tablespoon',
    'tanzanian shilling': 'TanzanianShilling',
    'teaspoon': 'Teaspoon',
    'tebi': 'Tebi',
    'technical atmosphere': 'AtmosphereTechnical',
    'tenge': 'Tenge',
    'tera': 'Tera',
    'tesla': 'Tesla',
    'tesla meter': 'TeslaMeter',
    'tesla second': 'TeslaSecond',
    'tex': 'Tex',
    'therm ec': 'ThermEEC',
    'therm us': 'ThermUS',
    'thermochemical calorie': 'CalorieThermochemical',
    'ton - long': 'TonLong',
    'ton - short': 'TonShort',
    'ton assay': 'TonAssay',
    'ton energy': 'TonEnergy',
    'ton long per cubic yard': 'TonLongPerCubicYard',
    'ton metric': 'TonMetric',
    'ton of oil equivalent': 'TonOfOilEquivalent',
    'ton of refrigeration': 'TonOfRefrigeration',
    'ton short per cubic yard': 'TonShortPerCubicYard',
    'torr': 'Torr',
    'trinidad and tobago dollar': 'TrinidadAndTobagoDollar',
    'tugrik': 'Tugrik',
    'tunisian dinar': 'TunisianDinar',
    'uganda shilling': 'UgandaShilling',
    'uic franc (special settlement currency)': 'UICFranc',
    'unidad de valor real': 'UnidadDeValorReal',
    'unidades de formento (funds code)': 'UnidadesDeFormento',
    'unified atomic mass unit': 'UnifiedAtomicMassUnit',
    'unit pole': 'UnitPole',
    'united arab emirates dirham': 'UAEDirham',
    'united states dollar (next day) (funds code)': 'USDollar-NextDay',
    'united states dollar (same day) (funds code)': 'USDollar-SameDay',
    'unitless': 'Unitless',
    'us customary unit system': 'SystemOfUnits_USCustomary',
    'us dollar': 'USDollar',
    'us dry pint': 'DryPintUS',
    'us dry quart': 'DryQuartUS',
    'us gallon': 'GallonUS',
    'us gallon per day': 'GallonUSPerDay',
    'us gallon per minute': 'GallonUSPerMinute',
    'us liquid cup': 'LiquidCupUS',
    'us liquid ounce': 'LiquidOunceUS',
    'us liquid pint': 'LiquidPintUS',
    'us liquid quart': 'LiquidQuartUS',
    'us peck': 'Peck',
    'us survey foot': 'FootUSSurvey',
    'uzbekistan som': 'UzbekistanSom',
    'vatu': 'Vatu',
    'venezuelan bolivar': 'VenezuelanBolivar',
    'video frame': 'VideoFrame',
    'vietnamese ??ng': 'VietnameseDong',
    'volt': 'Volt',
    'volt meter': 'VoltMeter',
    'volt per meter': 'VoltPerMeter',
    'volt per second': 'VoltPerSecond',
    'volt per square meter': 'VoltPerSquareMeter',
    'watt': 'Watt',
    'watt per meter kelvin': 'WattPerMeterKelvin',
    'watt per square centimeter': 'WattPerSquareCentimeter',
    'watt per square foot': 'WattPerSquareFoot',
    'watt per square inch': 'WattPerSquareInch',
    'watt per square meter': 'WattPerSquareMeter',
    'watt per square meter kelvin': 'WattPerSquareMeterKelvin',
    'watt per square meter quartic kelvin': 'WattPerSquareMeterQuarticKelvin',
    'watt per square meter steradian': 'WattPerSquareMeterSteradian',
    'watt per steradian': 'WattPerSteradian',
    'watt square meter': 'WattSquareMeter',
    'watt square meter per steradian': 'WattSquareMeterPerSteradian',
    'watthour': 'Watthour',
    'weber': 'Weber',
    'wir euro (complementary currency)': 'WIREuro',
    'wir franc (complementary currency)': 'WIRFranc',
    'yard': 'Yard',
    'year (365 day)': 'Year365Day',
    'year sidereal': 'YearSidereal',
    'year tropical': 'YearTropical',
    'yemeni rial': 'YemeniRial',
    'yobi': 'Yobi',
    'yocto': 'Yocto',
    'yotta': 'Yotta',
    'yuan renminbi': 'YuanRenminbi',
    'zambian kwacha': 'ZambianKwacha',
    'zebi': 'Zebi',
    'zepto': 'Zepto',
    'zetta': 'Zetta',
    'zimbabwe dollar': 'ZimbabweDollar',
    'zloty': 'Zloty',
}

namespace = 'http://qudt.org/vocab/unit#'

class qudt:
    def __getitem__(self, name):
        uri = name.lower().replace('_', ' ')
        if uri.endswith('metre'): uri = uri[:-5] + "meter"
        uri = unit_labels.get(uri, None)
        if uri: return namespace + uri
        else: return name
